Repository trezor/trezor-core, pull requests merged in 2018-03, with the labels that each got.

#148 passphrase: include all ASCII characters
  src/trezor/ui/passphrase.py
Labels: firmware, ui

#151 wallet/signing: segwit has priority over force_bip143
  src/apps/wallet/sign_tx/signing.py
Labels: firmware

#168 apps/wallet/{sign_identity, ecdh}: show protocol as part of the header
  src/apps/wallet/ecdh.py
  src/apps/wallet/sign_identity.py
Labels: enhancement, firmware
