Repository trezor/trezor-core, pull requests merged in 2018-06, with the labels that each got.

#174 firmware: disable WebUSB landing page
  embed/bootloader/main.c
  embed/extmod/modtrezorio/modtrezorio-usb.h
  embed/prodtest/main.c
  embed/trezorhal/usb.c
  embed/trezorhal/usb.h
  src/usb.py
Labels: enhancement, firmware

#179 NEM
  SConscript.firmware
  SConscript.unix
  embed/extmod/modtrezorcrypto/modtrezorcrypto-bip32.h
  embed/extmod/modtrezorcrypto/modtrezorcrypto-ed25519.h
  embed/extmod/modtrezorcrypto/modtrezorcrypto-nem.h
  embed/extmod/modtrezorcrypto/modtrezorcrypto.c
  mocks/generated/trezorconfig.py
  mocks/generated/trezorcrypto.py
  mocks/generated/trezorio.py
  mocks/generated/trezorui.py
  mocks/generated/trezorutils.py
  pytest.ini
  src/apps/nem/README.md
  src/apps/nem/__init__.py
  src/apps/nem/get_address.py
  src/apps/nem/helpers.py
  src/apps/nem/layout.py
  src/apps/nem/mosaic/__init__.py
  src/apps/nem/mosaic/helpers.py
  src/apps/nem/mosaic/layout.py
  src/apps/nem/mosaic/nem_mosaics.py
  src/apps/nem/mosaic/serialize.py
  src/apps/nem/multisig/__init__.py
  src/apps/nem/multisig/layout.py
  src/apps/nem/multisig/serialize.py
  src/apps/nem/namespace/__init__.py
  src/apps/nem/namespace/layout.py
  src/apps/nem/namespace/serialize.py
  src/apps/nem/signing.py
  src/apps/nem/transfer/__init__.py
  src/apps/nem/transfer/layout.py
  src/apps/nem/transfer/serialize.py
  src/apps/nem/validators.py
  src/apps/nem/writers.py
  src/main.py
  src/trezor/crypto/__init__.py
  tests/test_apps.nem.address.py
  tests/test_apps.nem.hdnode.py
  tests/test_apps.nem.mosaic.py
  tests/test_apps.nem.mosaic_creation.py
  tests/test_apps.nem.mosaic_supply_change.py
  tests/test_apps.nem.multisig.aggregate_modification.py
  tests/test_apps.nem.multisig.py
  tests/test_apps.nem.namespace.py
  tests/test_apps.nem.transfer.py
  tools/codegen/gen_nem_mosaics.py
Labels: altcoin, firmware

#213 Efficient text layout
  embed/extmod/modtrezorui/display.h
  embed/extmod/modtrezorui/modtrezorui-display.h
  src/trezor/ui/text.py
Labels: enhancement, firmware, ui

#233 NEM: display QR code in get address and display address refactoring
  src/apps/common/display_address.py
  src/apps/ethereum/get_address.py
  src/apps/ethereum/verify_message.py
  src/apps/lisk/get_address.py
  src/apps/nem/get_address.py
  src/apps/wallet/get_address.py
  src/apps/wallet/verify_message.py
Labels: altcoin, firmware

#248 embed/firmware: update linker to use firmware_extra section
  Makefile
  SConscript.firmware
  embed/firmware/memory.ld
Labels: enhancement, firmware
